import { ComparisonDataset } from './comparison.types';

export const mvpWaterPurifierDataset: ComparisonDataset = {
  brands: [
    { id: 'brand-coway', slug: 'coway', name: '코웨이' },
    { id: 'brand-lg', slug: 'lg', name: 'LG전자' },
    { id: 'brand-cuckoo', slug: 'cuckoo', name: '쿠쿠' },
  ],
  categories: [{ id: 'category-water-purifier', slug: 'water-purifier', name: '정수기' }],
  products: [
    {
      id: 'product-coway-icon-ice',
      brandId: 'brand-coway',
      categoryId: 'category-water-purifier',
      name: '아이콘 얼음정수기',
      modelName: '아이콘 얼음정수기',
      modelCode: 'CHPI-7400N',
      officialProductUrl: 'https://www.coway.com/product/detail?prdno=215',
      cashPrice: 1720000,
      status: 'active',
      specifications: {
        hasIce: true,
        temperatureModes: ['cold', 'hot', 'ice'],
        waterSourceType: 'direct_flow',
        installationType: 'countertop',
        widthMm: 260,
        depthMm: 520,
        heightMm: 515,
      },
    },
    {
      id: 'product-lg-objet-ice',
      brandId: 'brand-lg',
      categoryId: 'category-water-purifier',
      name: '오브제컬렉션 얼음정수기',
      modelName: '오브제컬렉션 얼음정수기',
      modelCode: 'WD524A',
      officialProductUrl:
        'https://www.lge.co.kr/business/care-solutions/water-purifiers/wd523vc?dpType=careTab',
      cashPrice: 1890000,
      status: 'active',
      specifications: {
        hasIce: true,
        temperatureModes: ['cold', 'hot', 'ice'],
        waterSourceType: 'direct_flow',
        installationType: 'countertop',
        widthMm: 270,
        depthMm: 530,
        heightMm: 520,
      },
    },
    {
      id: 'product-cuckoo-slim-coldhot',
      brandId: 'brand-cuckoo',
      categoryId: 'category-water-purifier',
      name: '슬림 냉온정수기',
      modelName: '슬림 냉온정수기',
      modelCode: 'CP-TS011',
      officialProductUrl: 'https://www.cuckoo.co.kr/rental/productView?idx=822',
      cashPrice: 1290000,
      status: 'active',
      specifications: {
        hasIce: false,
        temperatureModes: ['cold', 'hot'],
        waterSourceType: 'direct_flow',
        installationType: 'countertop',
        widthMm: 180,
        depthMm: 490,
        heightMm: 400,
      },
    },
  ],
  rentalPlans: [
    {
      id: 'plan-coway-visit-72',
      productId: 'product-coway-icon-ice',
      planName: '방문관리 72개월',
      managementType: 'visit',
      contractTermMonths: 72,
      obligationTermMonths: 72,
      ownershipTransferMonths: 72,
      baseMonthlyFee: 37900,
      promoMonthlyFee: 33900,
      totalContractCost: 2440800,
      registrationFee: 0,
      installationFee: 0,
      visitCycleMonths: 2,
      filterCycleMonths: 2,
      careSummary: '2개월 방문관리, 필터 교체 포함',
      officialCardDiscountAmount: 25000,
      officialCardRequiredSpendAmount: 300000,
      officialCardSummary: '월 30만원 사용 시 최대 2.5만원 할인',
      isActive: true,
    },
    {
      id: 'plan-coway-self-72',
      productId: 'product-coway-icon-ice',
      planName: '자가관리 72개월',
      managementType: 'self',
      contractTermMonths: 72,
      obligationTermMonths: 72,
      ownershipTransferMonths: 72,
      baseMonthlyFee: 32900,
      promoMonthlyFee: 30900,
      totalContractCost: 2224800,
      registrationFee: 0,
      installationFee: 0,
      visitCycleMonths: null,
      filterCycleMonths: 4,
      careSummary: '4개월 필터 배송, 자가교체',
      officialCardDiscountAmount: 25000,
      officialCardRequiredSpendAmount: 300000,
      officialCardSummary: '월 30만원 사용 시 최대 2.5만원 할인',
      isActive: true,
    },
    {
      id: 'plan-lg-visit-60',
      productId: 'product-lg-objet-ice',
      planName: '방문관리 60개월',
      managementType: 'visit',
      contractTermMonths: 60,
      obligationTermMonths: 60,
      ownershipTransferMonths: 60,
      baseMonthlyFee: 39900,
      promoMonthlyFee: 37900,
      totalContractCost: 2274000,
      registrationFee: 0,
      installationFee: 0,
      visitCycleMonths: 6,
      filterCycleMonths: 6,
      careSummary: '6개월 방문관리, 필터 교체 포함',
      officialCardDiscountAmount: 23000,
      officialCardRequiredSpendAmount: 300000,
      officialCardSummary: '제휴카드 최대 2.3만원 할인',
      isActive: true,
    },
    {
      id: 'plan-cuckoo-self-60',
      productId: 'product-cuckoo-slim-coldhot',
      planName: '자가관리 60개월',
      managementType: 'self',
      contractTermMonths: 60,
      obligationTermMonths: 60,
      ownershipTransferMonths: 60,
      baseMonthlyFee: 25900,
      promoMonthlyFee: 23900,
      totalContractCost: 1434000,
      registrationFee: 0,
      installationFee: 0,
      visitCycleMonths: null,
      filterCycleMonths: 4,
      careSummary: '4개월 필터 배송, 자가교체',
      officialCardDiscountAmount: 20000,
      officialCardRequiredSpendAmount: 300000,
      officialCardSummary: '제휴카드 최대 2만원 할인',
      isActive: true,
    },
  ],
  contractPolicies: [
    {
      id: 'policy-coway-visit-72',
      rentalPlanId: 'plan-coway-visit-72',
      earlyTerminationAllowed: true,
      penaltySummary: '잔여 의무기간 기준 위약금 및 할인반환금 부과',
      pickupFee: 30000,
      ownershipEndType: 'transfer',
      notes: '만기 시 소유권 이전',
    },
    {
      id: 'policy-coway-self-72',
      rentalPlanId: 'plan-coway-self-72',
      earlyTerminationAllowed: true,
      penaltySummary: '잔여 의무기간 기준 위약금 및 할인반환금 부과',
      pickupFee: 30000,
      ownershipEndType: 'transfer',
      notes: '만기 시 소유권 이전',
    },
    {
      id: 'policy-lg-visit-60',
      rentalPlanId: 'plan-lg-visit-60',
      earlyTerminationAllowed: true,
      penaltySummary: '잔여기간에 따른 해약금 및 할인반환금 부과',
      pickupFee: 30000,
      ownershipEndType: 'transfer',
      notes: '계약 완료 후 소유권 이전',
    },
    {
      id: 'policy-cuckoo-self-60',
      rentalPlanId: 'plan-cuckoo-self-60',
      earlyTerminationAllowed: true,
      penaltySummary: '해지 시 할인반환금 및 철거비 발생 가능',
      pickupFee: 30000,
      ownershipEndType: 'transfer',
      notes: '소유권 이전형 렌탈',
    },
  ],
  salesChannels: [
    {
      id: 'channel-ajd',
      slug: 'ajd',
      name: '아정당',
      channelType: 'comparison_market',
      websiteUrl: 'https://www.ajd.co.kr',
    },
    {
      id: 'channel-miso',
      slug: 'miso',
      name: '미소',
      channelType: 'comparison_market',
      websiteUrl: 'https://miso.kr',
    },
    {
      id: 'channel-rentre',
      slug: 'rentre',
      name: '렌트리',
      channelType: 'comparison_market',
      websiteUrl: 'https://rentre.kr',
    },
    {
      id: 'channel-billigo',
      slug: 'billigo',
      name: '빌리고',
      channelType: 'comparison_market',
      websiteUrl: 'https://m.billigo.kr',
    },
  ],
  channelOffers: [
    {
      id: 'offer-coway-visit-ajd-fixed',
      salesChannelId: 'channel-ajd',
      productId: 'product-coway-icon-ice',
      rentalPlanId: 'plan-coway-visit-72',
      offerName: '코웨이 아이콘 얼음정수기 방문관리',
      publicOfferUrl: 'https://www.ajd.co.kr/electronics/overview/4020/detail/42950',
      publicMonthlyFee: 33900,
      nonCardMonthlyFee: 33900,
      cardAppliedMonthlyFee: 8900,
      supportPricingModel: 'fixed_public',
      supportAmount: 120000,
      supportAmountMin: null,
      supportAmountMax: null,
      payoutTiming: 'after_install',
      payoutMethod: 'cash',
      installDayPayout: false,
      benefitGuaranteeType: 'platform',
      matchingStatus: 'auto_matched',
      matchingConfidence: 0.98,
      reviewStatus: 'approved',
      reviewNote: '공개 고정 지원금 확인',
      status: 'active',
      firstSeenAt: '2026-03-26T10:00:00.000Z',
      lastSeenAt: '2026-03-27T10:00:00.000Z',
      metadata: { sellerName: '아정당 공식 비교', sourcePriority: 1 },
    },
    {
      id: 'offer-coway-visit-rentre-range',
      salesChannelId: 'channel-rentre',
      productId: 'product-coway-icon-ice',
      rentalPlanId: 'plan-coway-visit-72',
      offerName: '코웨이 아이콘 얼음정수기 방문관리',
      publicOfferUrl: 'https://rentre.kr/product/brand/COWAY/WATER_PURIFIER',
      publicMonthlyFee: 32900,
      nonCardMonthlyFee: 32900,
      cardAppliedMonthlyFee: 7900,
      supportPricingModel: 'range_public',
      supportAmount: null,
      supportAmountMin: 100000,
      supportAmountMax: 150000,
      payoutTiming: 'after_install',
      payoutMethod: 'cash',
      installDayPayout: false,
      benefitGuaranteeType: 'platform',
      matchingStatus: 'auto_matched',
      matchingConfidence: 0.96,
      reviewStatus: 'approved',
      reviewNote: '예상 혜택 범위 노출 확인',
      status: 'active',
      firstSeenAt: '2026-03-26T10:00:00.000Z',
      lastSeenAt: '2026-03-27T10:00:00.000Z',
      metadata: { sellerName: '렌트리 비교', sourcePriority: 3 },
    },
    {
      id: 'offer-coway-visit-billigo-quote',
      salesChannelId: 'channel-billigo',
      productId: 'product-coway-icon-ice',
      rentalPlanId: 'plan-coway-visit-72',
      offerName: '코웨이 아이콘 얼음정수기 방문관리',
      publicOfferUrl: 'https://m.billigo.kr/shop/view.php?index_no=68067',
      publicMonthlyFee: 31900,
      nonCardMonthlyFee: 31900,
      cardAppliedMonthlyFee: 6900,
      supportPricingModel: 'quote_required',
      supportAmount: null,
      supportAmountMin: null,
      supportAmountMax: null,
      payoutTiming: 'unknown',
      payoutMethod: 'unknown',
      installDayPayout: false,
      benefitGuaranteeType: 'unclear',
      matchingStatus: 'manually_matched',
      matchingConfidence: 0.88,
      reviewStatus: 'approved',
      reviewNote: '해피콜 시 확인 표기',
      status: 'active',
      firstSeenAt: '2026-03-26T10:00:00.000Z',
      lastSeenAt: '2026-03-27T10:00:00.000Z',
      metadata: { sellerName: '빌리고 모바일', sourcePriority: 4 },
    },
    {
      id: 'offer-coway-visit-miso-hidden-pending',
      salesChannelId: 'channel-miso',
      productId: 'product-coway-icon-ice',
      rentalPlanId: 'plan-coway-visit-72',
      offerName: '코웨이 아이콘 얼음정수기 방문관리',
      publicOfferUrl: 'https://miso.kr/booking/rental/water_purifier/WD526A?brand=coway',
      publicMonthlyFee: 33500,
      nonCardMonthlyFee: 33500,
      cardAppliedMonthlyFee: 9500,
      supportPricingModel: 'hidden',
      supportAmount: null,
      supportAmountMin: null,
      supportAmountMax: null,
      payoutTiming: 'unknown',
      payoutMethod: 'unknown',
      installDayPayout: false,
      benefitGuaranteeType: 'unclear',
      matchingStatus: 'low_confidence',
      matchingConfidence: 0.61,
      reviewStatus: 'pending',
      reviewNote: '검수 대기',
      status: 'active',
      firstSeenAt: '2026-03-26T10:00:00.000Z',
      lastSeenAt: '2026-03-27T10:00:00.000Z',
      metadata: { sellerName: '미소 비교', sourcePriority: 2 },
    },
    {
      id: 'offer-coway-self-ajd-range',
      salesChannelId: 'channel-ajd',
      productId: 'product-coway-icon-ice',
      rentalPlanId: 'plan-coway-self-72',
      offerName: '코웨이 아이콘 얼음정수기 자가관리',
      publicOfferUrl: 'https://www.ajd.co.kr/electronics/overview/4020/detail/42950?care=self',
      publicMonthlyFee: 29900,
      nonCardMonthlyFee: 29900,
      cardAppliedMonthlyFee: 5900,
      supportPricingModel: 'range_public',
      supportAmount: null,
      supportAmountMin: 50000,
      supportAmountMax: 80000,
      payoutTiming: 'after_install',
      payoutMethod: 'cash',
      installDayPayout: false,
      benefitGuaranteeType: 'platform',
      matchingStatus: 'auto_matched',
      matchingConfidence: 0.94,
      reviewStatus: 'approved',
      reviewNote: '자가관리 오퍼 확인',
      status: 'active',
      firstSeenAt: '2026-03-26T10:00:00.000Z',
      lastSeenAt: '2026-03-27T10:00:00.000Z',
      metadata: { sellerName: '아정당 공식 비교', sourcePriority: 1 },
    },
    {
      id: 'offer-lg-visit-miso-fixed',
      salesChannelId: 'channel-miso',
      productId: 'product-lg-objet-ice',
      rentalPlanId: 'plan-lg-visit-60',
      offerName: 'LG 오브제컬렉션 얼음정수기 방문관리',
      publicOfferUrl: 'https://miso.kr/booking/rental/water_purifier/WD526A',
      publicMonthlyFee: 36900,
      nonCardMonthlyFee: 36900,
      cardAppliedMonthlyFee: 13900,
      supportPricingModel: 'fixed_public',
      supportAmount: 180000,
      supportAmountMin: null,
      supportAmountMax: null,
      payoutTiming: 'after_install',
      payoutMethod: 'cash',
      installDayPayout: false,
      benefitGuaranteeType: 'platform',
      matchingStatus: 'auto_matched',
      matchingConfidence: 0.95,
      reviewStatus: 'approved',
      reviewNote: '고정 지원금 확인',
      status: 'active',
      firstSeenAt: '2026-03-26T10:00:00.000Z',
      lastSeenAt: '2026-03-27T10:00:00.000Z',
      metadata: { sellerName: '미소 비교', sourcePriority: 2 },
    },
    {
      id: 'offer-lg-visit-rentre-range',
      salesChannelId: 'channel-rentre',
      productId: 'product-lg-objet-ice',
      rentalPlanId: 'plan-lg-visit-60',
      offerName: 'LG 오브제컬렉션 얼음정수기 방문관리',
      publicOfferUrl: 'https://rentre.kr/product/brand/LG/WATER_PURIFIER',
      publicMonthlyFee: 35900,
      nonCardMonthlyFee: 35900,
      cardAppliedMonthlyFee: 10900,
      supportPricingModel: 'range_public',
      supportAmount: null,
      supportAmountMin: 0,
      supportAmountMax: 220000,
      payoutTiming: 'after_install',
      payoutMethod: 'cash',
      installDayPayout: false,
      benefitGuaranteeType: 'platform',
      matchingStatus: 'auto_matched',
      matchingConfidence: 0.92,
      reviewStatus: 'approved',
      reviewNote: '최대 지원금 기반 범위 처리',
      status: 'active',
      firstSeenAt: '2026-03-26T10:00:00.000Z',
      lastSeenAt: '2026-03-27T10:00:00.000Z',
      metadata: { sellerName: '렌트리 비교', sourcePriority: 3 },
    },
    {
      id: 'offer-cuckoo-self-billigo-hidden',
      salesChannelId: 'channel-billigo',
      productId: 'product-cuckoo-slim-coldhot',
      rentalPlanId: 'plan-cuckoo-self-60',
      offerName: '쿠쿠 슬림 냉온정수기 자가관리',
      publicOfferUrl: 'https://m.billigo.kr/shop/view.php?index_no=57001',
      publicMonthlyFee: 23900,
      nonCardMonthlyFee: 23900,
      cardAppliedMonthlyFee: 3900,
      supportPricingModel: 'hidden',
      supportAmount: null,
      supportAmountMin: null,
      supportAmountMax: null,
      payoutTiming: 'unknown',
      payoutMethod: 'unknown',
      installDayPayout: false,
      benefitGuaranteeType: 'unclear',
      matchingStatus: 'manually_matched',
      matchingConfidence: 0.86,
      reviewStatus: 'approved',
      reviewNote: '혜택 문구만 있고 금액 없음',
      status: 'active',
      firstSeenAt: '2026-03-26T10:00:00.000Z',
      lastSeenAt: '2026-03-27T10:00:00.000Z',
      metadata: { sellerName: '빌리고 모바일', sourcePriority: 4 },
    },
    {
      id: 'offer-cuckoo-self-ajd-fixed-rejected',
      salesChannelId: 'channel-ajd',
      productId: 'product-cuckoo-slim-coldhot',
      rentalPlanId: 'plan-cuckoo-self-60',
      offerName: '쿠쿠 슬림 냉온정수기 자가관리',
      publicOfferUrl: 'https://www.ajd.co.kr/electronics/overview/4020/detail/42951',
      publicMonthlyFee: 24900,
      nonCardMonthlyFee: 24900,
      cardAppliedMonthlyFee: 4900,
      supportPricingModel: 'fixed_public',
      supportAmount: 70000,
      supportAmountMin: null,
      supportAmountMax: null,
      payoutTiming: 'after_install',
      payoutMethod: 'cash',
      installDayPayout: false,
      benefitGuaranteeType: 'platform',
      matchingStatus: 'low_confidence',
      matchingConfidence: 0.52,
      reviewStatus: 'rejected',
      reviewNote: '상품 매칭 오인식으로 반려',
      status: 'active',
      firstSeenAt: '2026-03-26T10:00:00.000Z',
      lastSeenAt: '2026-03-27T10:00:00.000Z',
      metadata: { sellerName: '아정당 공식 비교', sourcePriority: 1 },
    },
  ],
  offerBenefits: [
    {
      id: 'benefit-coway-ajd-giftcard',
      channelOfferId: 'offer-coway-visit-ajd-fixed',
      benefitType: 'giftcard',
      valueModel: 'fixed',
      amount: 30000,
      amountMin: null,
      amountMax: null,
      description: '신세계 상품권 3만원',
      conditions: '설치 완료 후 지급',
      payoutTiming: 'after_install',
      payoutMethod: 'giftcard',
      sourceType: 'page',
      isActive: true,
    },
    {
      id: 'benefit-coway-rentre-fee-waiver',
      channelOfferId: 'offer-coway-visit-rentre-range',
      benefitType: 'fee_waiver',
      valueModel: 'fixed',
      amount: 0,
      amountMin: null,
      amountMax: null,
      description: '설치비 면제',
      conditions: '프로모션 기간 내 신청 시',
      payoutTiming: 'same_day',
      payoutMethod: 'unknown',
      sourceType: 'page',
      isActive: true,
    },
    {
      id: 'benefit-lg-miso-product-gift',
      channelOfferId: 'offer-lg-visit-miso-fixed',
      benefitType: 'product_gift',
      valueModel: 'hidden',
      amount: null,
      amountMin: null,
      amountMax: null,
      description: '생활가전 사은품 증정',
      conditions: '재고 소진 시 종료',
      payoutTiming: 'after_install',
      payoutMethod: 'product',
      sourceType: 'page',
      isActive: true,
    },
    {
      id: 'benefit-cuckoo-billigo-first-month',
      channelOfferId: 'offer-cuckoo-self-billigo-hidden',
      benefitType: 'first_month_free',
      valueModel: 'fixed',
      amount: 23900,
      amountMin: null,
      amountMax: null,
      description: '첫 달 렌탈료 면제',
      conditions: '자동이체 등록 시',
      payoutTiming: 'after_confirmation',
      payoutMethod: 'cash',
      sourceType: 'page',
      isActive: true,
    },
  ],
};
